### ISSUE TITLE
About patch

### ISSUE THREAD

**Issue by RohitVerma882** [nohajc/vendor-adb-patched#1]
Can you write termux-adb in c/c++ not in rust.
I want to understand how termux-adb works

**Comment by RohitVerma882** [comment]
I want to modify adb for android but I'm didn't know how to do that.
I know only basics of c/c++

**Comment by nohajc** [comment]
Hi, it could be done in C++ but it was easier for me to do it in Rust because of the library ecosystem and dependency management (cargo).

I think you should be able to understand the principle behind it from reading the Rust code as well.

Anyway, you said earlier you wanted to build a full app around it, right? So rather than rewriting it yourself, maybe you only need to write a frontend for it.

The way I see it, one could take `termux-adb` and turn it into a fully-fledged library which could be linked to a Java/Kotlin app. Of course in that case, it would also make sense to directly call Android API which is used by `termux-usb`. I haven't looked into that but it might be interesting.

**Comment by nohajc** [comment]
If you want to see how the C++ code in adb interacts with libtermuxadb, take a look at https://github.com/nohajc/vendor-adb-patched/blob/master/vendor/adb/client/usb_linux.cpp

I replaced some function calls with my own versions located in `termuxadb` namespace.

**Comment by RohitVerma882** [comment]
For now, I am making an app for fastboot, but I need help in modifying the c++ code of fastboot.

Project: https://github.com/RohitVerma882/Flashi
Fastboot: https://github.com/RohitVerma882/fastboot
